# Generated by Django 5.2.3 on 2025-07-02 05:29

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid_description', models.TextField(blank=True, null=True)),
                ('delivery_days', models.PositiveIntegerField(help_text='Delivery time in days')),
                ('related_documents', models.FileField(null=True, upload_to='bid_related_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='bid_request_documents/')),
                ('related_image', models.ImageField(upload_to='bid_request_related_images/', validators=[auction.models.validate_image_size])),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(help_text='e.g., pieces, kg, liters', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('delivery_deadline', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_awarded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
