# Generated by Django 5.2.3 on 2025-07-02 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='winning_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction', to='auction.bid'),
        ),
        migrations.AddField(
            model_name='bidrequest',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='auction.bidrequest'),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='bid_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='auction.bidrequest'),
        ),
        migrations.AddField(
            model_name='bidrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auction.category'),
        ),
        migrations.AddField(
            model_name='bidrequest',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('vendor', 'bid_request')},
        ),
    ]
